---
#Ref: https://github.com/Mintplex-Labs/anything-llm/blob/master/docker/.env.example
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.model.name }}-vllm-cpu
  labels:
    opendatahub.io/dashboard: 'true'
  annotations:
    opendatahub.io/connection-type-ref: anythingllm-generic-openai
    openshift.io/description: Connect to a {{ .Values.model.name }} model
    openshift.io/display-name: vLLM CPU {{ .Values.model.name }}
data:
  DISABLE_TELEMETRY: {{ "true" | b64enc }}
  EMBEDDING_ENGINE: {{ "native" | b64enc }}
  LLM_PROVIDER: {{ "generic-openai" | b64enc }}
  GENERIC_OPEN_AI_API_KEY: {{ "sk-dummy" | b64enc }}
  GENERIC_OPEN_AI_BASE_PATH: {{ printf "http://%s-cpu-predictor:8080/v1" .Values.model.name | b64enc }}
  GENERIC_OPEN_AI_MODEL_PREF: {{ .Values.model.name | b64enc }}
  GENERIC_OPEN_AI_MODEL_TOKEN_LIMIT: {{ "512" | b64enc }}
  VECTOR_DB: {{ "lancedb" | b64enc }}
type: Opaque